### ISSUE TITLE
Add eslint-plugin-import as a default plugin

### ISSUE THREAD

**Issue by NoxHarmonium** [danielnixon/eslint-config-typed-fp#13]
eslint-plugin-import has some useful default rules to prevent things like cyclic dependencies and importing dependencies that aren't in your package.json dependency list.

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-default-export.md also seems good to avoid having the name of the import drift from the name of the module after refactoring

**Comment by danielnixon** [comment]
Related: https://basarat.gitbook.io/typescript/main-1/defaultisbad

**Comment by danielnixon** [comment]
Closing this one, it's done over at https://github.com/agiledigital-labs/eslint-config-agile-digital
