### ISSUE TITLE
Ban enums by default

### ISSUE THREAD

**Issue by NoxHarmonium** [danielnixon/eslint-config-typed-fp#284]
Discriminated unions are a better choice than enums in 95% of cases but they are overused by developers coming from other languages like C# who see them as familiar.

I think it would be good to ban enums by default, and allow exceptions in the rare cases where they are appropriate.

More explanation: https://stackoverflow.com/a/60041791/1153203

**Comment by danielnixon** [comment]
Depending on how complicated the implementation is, the proposed rule may be better off in https://github.com/danielnixon/eslint-plugin-total-functions

**Comment by danielnixon** [comment]
More: https://github.com/typescript-eslint/typescript-eslint/issues/561

**Comment by danielnixon** [comment]
Done is latest release.
